# Map labels to file path globs. Applied automatically on PRs.
frontend:
  - 'frontend/**'
  - 'apps/web/**'
backend:
  - 'backend/**'
  - 'services/**'
infrastructure:
  - 'infra/**'
  - 'deploy/**'
  - 'docker/**'
  - '**/Dockerfile'
documentation:
  - 'docs/**'
  - '**/*.md'
bug:
  - 'fix/**'
feature:
  - 'feature/**'
refactor:
  - 'refactor/**'
