global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'email-gateway'
    environment: 'development'

# Load alert rules
rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'email-gateway-api'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'email-gateway-worker'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
